---
title: "Final_Project_BISC"
author: "Sarah Elizabeth Stockman"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("neonUtilities")

# Set global option to NOT convert all character variables to factors, which helps to make the NEON functions to work best
options(stringsAsFactors=F)

# Load required packages
library(neonUtilities)
library(tidyverse)
require(plyr)
require(dplyr)
require(tidyverse)
require(corrplot)
require(ggplot2)
library(raster)
library(rgdal)
library(ggplot2)
library(dplyr)
library(sf)
```


```{r}

#AOP

#Read in all available veg itation data
vegitation_data <- loadByProduct(dpID = "DP1.10098.001", startdate = "2016-01", enddate = "2020-06",check.size = F, site= c("OSBS"))

# Unlist vegitation_data to Rstudio environment 
list2env(vegitation_data, .GlobalEnv)

# Get plot centroids
OSBS_centroids <- vst_perplotperyear %>%
  dplyr::filter(siteID == "OSBS") %>%
  dplyr::select(siteID, plotID, easting, northing, utmZone, nlcdClass) %>%
  dplyr::distinct()
utm17nCRS <- "+proj=utm +zone=17 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

# Convert data frame to sf object
OSBS_centroids_sp <- st_as_sf(OSBS_centroids, 
                              coords = c("easting", "northing"), crs = utm17nCRS)


```


Download the AOP tiles that correspond to OSBS forest plots: 
```{r}
# Before you download, delete any files in the DP3.30015.001/ data path
#pre-huricaine
byTileAOP(dpID="DP3.30015.001", site="OSBS", 
          year="2017", 
          easting = OSBS_centroids$easting,
          northing = OSBS_centroids$northing)

#post-huricaine          
byTileAOP(dpID="DP3.30015.001", site="OSBS", year="2018", 
         easting = OSBS_centroids$easting,
          northing = OSBS_centroids$northing)

```


Calculate the CHM values in the pre-hurricane data for each forest plot: 
```{r}
# Set the file prefix for the 2017 CHM data path
file_prefix_17 <- "DP3.30015.001/2017/FullSite/D03/2017_OSBS_3/L3/DiscreteLidar/CanopyHeightModelGtif/"

# List the CHM files in the 2017 data path
OSBS_chmTiles_17 <- list.files(file_prefix_17)

# Loop over the CHM tiles: 
# 1. Find the matching plots for each tile
# 2. Calculate the stat of interest for each plot
# 3. Build a data frame with the CHM values in plots
for(t in 1:length(OSBS_chmTiles_17)){
  
  # Load one tile
  OSBS_chm_tile <- raster(paste0(file_prefix_17, OSBS_chmTiles_17[t]))
  
  # Get the tile boundary box
  tile_bbox <- bbox(OSBS_chm_tile)
  
  # Match the tile coordinates to the plot
  tile_plots_match <- filter(OSBS_centroids, 
                       easting > tile_bbox[1,1] & easting < tile_bbox[1,2],
                       northing > tile_bbox[2,1] & northing < tile_bbox[2,2])
  
  # Filter the plot shapefile for the plots that match
  tile_plots <- dplyr::filter(OSBS_centroids_sp, plotID %in% tile_plots_match$plotID)
  
  # Extract the mean and variance 
  plot_chmMean <- raster::extract(x = OSBS_chm_tile, 
                                  y = tile_plots, fun = mean,
                                  buffer = 20,
                                  na.rm=TRUE)
  
  plot_chmVar <- raster::extract(x = OSBS_chm_tile, 
                                  y = tile_plots, fun = var,
                                  buffer = 20,
                                  na.rm=TRUE)
  
  # Build data frame with mean plot CHM values
  if(t == 1){
    plots_chmMean_preHurr <- data.frame(siteID = tile_plots$siteID,
                                        plotID = tile_plots$plotID,
                                        nlcdClass = tile_plots$nlcdClass,
                                        CHM_pre_mean = plot_chmMean,
                                        CHM_pre_var = plot_chmVar)
  } else {
    tmp <- data.frame(siteID = tile_plots$siteID,
                      plotID = tile_plots$plotID,
                      nlcdClass = tile_plots$nlcdClass,
                      CHM_pre_mean = plot_chmMean,
                      CHM_pre_var = plot_chmVar)
    plots_chmMean_preHurr <- bind_rows(plots_chmMean_preHurr, tmp)
  }
}
```

Calculate the CHM values in the post-hurricane data for each forest plot:
```{r}
# Set the file prefix for the 2018 CHM data path
file_prefix_18 <- "DP3.30015.001/2018/FullSite/D03/2018_OSBS_4/L3/DiscreteLidar/CanopyHeightModelGtif/"

# List the tiles that are in the file path
OSBS_chmTiles_18 <- list.files(file_prefix_18)

# Loop over the CHM tiles: 
# 1. Find the matching plots for each tile
# 2. Calculate the stat of interest for each plot
# 3. Build a data frame with the CHM values in plots
for(t in 1:length(OSBS_chmTiles_18)){
  
  # Load one tile
  OSBS_chm_tile <- raster(paste0(file_prefix_18, OSBS_chmTiles_18[t]))
  
  # Get the tile boundary box
  tile_bbox <- bbox(OSBS_chm_tile)
  
  # Match the tile coordinates to the plot
  tile_plots_match <- filter(OSBS_centroids, 
                       easting > tile_bbox[1,1] & easting < tile_bbox[1,2],
                       northing > tile_bbox[2,1] & northing < tile_bbox[2,2])
  
  # Filter the plot shapefile for the plots that match
  tile_plots <- dplyr::filter(OSBS_centroids_sp, plotID %in% tile_plots_match$plotID)
  
  # Extract the mean and variance 

  plot_chmMean <- raster::extract(x = OSBS_chm_tile, 
                                  y = tile_plots, fun = mean,
                                  buffer = 20, na.rm=TRUE)
  
  plot_chmVar <- raster::extract(x = OSBS_chm_tile, 
                                  y = tile_plots, fun = var,
                                  buffer = 20,
                                  na.rm=TRUE)
  
  # Build data frame with mean plot CHM values
  if(t == 1){
    plots_chmMean_postHurr <- data.frame(siteID = tile_plots$siteID,
                                        plotID = tile_plots$plotID,
                                        nlcdClass = tile_plots$nlcdClass,
                                        CHM_post_mean = plot_chmMean,
                                        CHM_post_var = plot_chmVar )
  } else {
    tmp <- data.frame(siteID = tile_plots$siteID,
                      plotID = tile_plots$plotID,
                      nlcdClass = tile_plots$nlcdClass,
                      CHM_post_mean = plot_chmMean,
                      CHM_post_var = plot_chmVar )
    plots_chmMean_postHurr <- bind_rows(plots_chmMean_postHurr, tmp)
  }
}


```

Combine the pre/post-disturbance CHM data
```{r}
# Combine pre and post data into one data frame
plots_chmMean_preHurr = plots_chmMean_preHurr %>% mutate(disturbance = "before")%>%  dplyr::rename(mean_CHM_plot = CHM_pre_mean, var_CHM_plot = CHM_pre_var) 
plots_chmMean_postHurr = plots_chmMean_postHurr %>% mutate(disturbance = "after") %>%  dplyr::rename(mean_CHM_plot = CHM_post_mean, var_CHM_plot = CHM_post_var)
plots_chmMean_all <- full_join(plots_chmMean_preHurr, plots_chmMean_postHurr)



```

calculate diversity metric and combine to CHM data
```{r}

# Calculate the diversity metrics
diversity_data =  vst_mappingandtagging%>%
  dplyr::select(date, domainID, siteID, plotID, individualID, taxonID)%>%mutate( year = format(date, "%Y"))#%>%
  #group_by( plotID)%>%
  #mutate(species_rich = n_distinct(taxonID))

aggregate_SR <- aggregate(data=diversity_data,  taxonID ~ plotID,  function(x) length(unique(x)))
colnames(aggregate_SR) <- c("plotID", "species_richness")
#species_rich_data = join(diversity_data, aggregate_SR, by="plotID")



# OSBS SR
OSBS_SR <- aggregate_SR[grep("OSBS",aggregate_SR$plotID),]

# Combine SR data to CHM data
plots_chmMean_SR <- left_join(plots_chmMean_all, OSBS_SR)
```








```{r}





npp_data = vst_apparentindividual%>%
  filter(measurementHeight == 130) %>%
  dplyr::select(date, domainID, siteID, plotID, individualID, plantStatus, stemDiameter)%>%
  mutate( year = format(date, "%Y"))

count = count(npp_data$individualID)
#mutate (basal area for each stem, dbh/2 ^2 * pi)
#changes in total live basal area instead of ANPP, filtering alive, basal area = calculate basal area dbh cm^2 (tree area)/m^2 (ground area)
#then add up, then divide by plot area: 20m x 20m (0.04 ha)

#npp_data%>% group_by(siteID, date["%Y"])%>% summarise(count = count(plotID))



###### find nearest ####
##### tower plot ###


#Hurricane Irma: Aug 30, 2017 – Sep 12, 2017
OSBS_veg = npp_data%>%filter(siteID == "OSBS")%>%mutate( disturbance = (ifelse ((year<2018), "before" ,"after")))

OSBS_veg_pre = OSBS_veg%>%filter(disturbance == "before")
OSBS_veg_post = OSBS_veg%>%filter(disturbance == "after")
#mutate( if (year<2017) {disturbance = "before"} else if (year>=2017) {disturbance = "after"})
#count_OSBS = count(OSBS_veg$individualID)
#OSBS_veg_pre[with(OSBS_veg_pre, order(date, plotID)), ]
single_OSBS_veg_pre = OSBS_veg_pre[!duplicated(OSBS_veg_pre[,c("individualID")]),]
single_OSBS_veg_post = OSBS_veg_post[!duplicated(OSBS_veg_post[,c("individualID")]),]

OSBS_diameter_data = full_join(single_OSBS_veg_pre, single_OSBS_veg_post)%>%
  mutate(tree_basal_area = ((stemDiameter/2) ^2 * pi))
 
OSBS_basal_area =  OSBS_diameter_data %>% dplyr::group_by(plotID, disturbance) %>%dplyr::summarise(n = n(), plot_basal_area_hect = sum(tree_basal_area)/ (.4))




#sum(is.na(single_OSBS_veg_post$stemDiameter))

# Hurricane Michael: October 7, 2018 – October 16, 2018
#JERC = npp_data%>%filter(siteID == "JERC")%>%mutate( disturbance = (ifelse ((year<2018), "before" ,"after")))


################# NEED TO FIGURE OUT HOW TO DIVIDE BY MID-YEAR###################
# Huricane Maria: Sep 16, 2017 – Oct 2, 2017
#GUAN = npp_data%>%filter(siteID == "GUAN")
#test2 = GUAN%>%filter(year==2017)


################# MAYBE CUT OUT ##################
#############
# wildfire November 13-16, 2016
#GRSM = npp_data%>%filter(siteID == "GRSM")
#test3 = GRSM%>%filter(year==2016)


# "live" %in% tag


full_data_CHM_SR_BA = left_join(plots_chmMean_SR, OSBS_basal_area)

```






graphs
```{r}
#boxplot of mean canopy height before and after a huricaine disturbance
ggplot(full_data_CHM_SR_BA)+
  geom_boxplot(aes(x = disturbance, y = plot_basal_area_hect))+
  labs(x = "x title", y = "plot basal area (cm^2/hectare)") + 
  theme_bw()+ theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank())
    #theme(text = element_text(size=10),
        #axis.text.x = element_text(angle=50, hjust=1), axis.title.y = element_text( hjust=-.3))


#boxplot of mean basal area before and after a huricaine disturbance
ggplot(full_data_CHM_SR_BA)+
  geom_boxplot(aes(x = disturbance, y = mean_CHM_plot))+
  labs(x = "x title", y = "mean canopy height (m)") + 
  theme_bw()+ theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggplot(full_data_CHM_SR_BA)+
  geom_boxplot(aes(x = disturbance, y = var_CHM_plot))+
  labs(x = "x title", y = "mean canopy height (m)") + 
  theme_bw()+ theme( panel.grid.major = element_blank(), panel.grid.minor = element_blank())


ggplot(full_data_CHM_SR_BA)+
  geom_point(aes(x = species_richness, y = plot_basal_area_hect, color= disturbance))

ggplot(full_data_CHM_SR_BA)+
  geom_point(aes(x = mean_CHM_plot, y = plot_basal_area_hect, color= disturbance))



```



statistical test

```{r}
#ancova model

biomass_model = lm(plot_basal_area_hect ~ disturbance + species_richness + mean_CHM_plot + var_CHM_plot, data = full_data_CHM_SR_BA) #fu
summary(biomass_model)

step(biomass_model,  direction="both", trace=1, steps=1000, k = 2)


#t.test(y = plot_basal_area_hect, x = disturbance, paired = TRUE, data= full_data_CHM_SR_BA)

#check predictor variables are not correlated
library("usdm")
vifstep(na.omit(cbind( full_data_CHM_SR_BA$species_richness , full_data_CHM_SR_BA$mean_CHM_plot , full_data_CHM_SR_BA$var_CHM_plot)), th = 10)



reduced_model = lm(plot_basal_area_hect ~ species_richness + mean_CHM_plot + species_richness : mean_CHM_plot, data = full_data_CHM_SR_BA)

summary(reduced_model)
anova(reduced_model)
reduced_model2= lm(plot_basal_area_hect ~ species_richness + mean_CHM_plot + species_richness : mean_CHM_plot + as.factor(disturbance), data = full_data_CHM_SR_BA)
````